### ISSUE TITLE
Add documentation for partitioning

### ISSUE THREAD

**Issue by abuhuraira0099** [Vanilla-OS/handbook#76] opened 2023-03-12 13:24 UTC
Documentate how partitioning should be done, what is the recommended way to do this and how to properly configure partitions to get a working VanillaOS installation etc.

**Comment by kbdharun** [comment] 2023-03-12 13:28
Duplicate of https://github.com/Vanilla-OS/handbook/issues/73

I will add the instruction today, sorry for the delay.

**Closed by kbdharun** 2023-03-12 13:28 UTC
